In [1]:
#第一種方法

In [2]:
import numpy as np

In [3]:
def shuffle_in_unison_scary(a, b):
    rng_state = np.random.get_state()
    np.random.shuffle(a)
    np.random.set_state(rng_state)
    np.random.shuffle(b)

In [4]:
a = np.array([
     [[0, 1], [1, 1], [1, 1]],
     [[1, 8], [9, 10], [11, 12]],
     [[2, 14], [15, 16], [17, 18]]
     ])
b = np.asarray([0, 1, 2])
shuffle_in_unison_scary(a, b)

In [5]:
print(a)
print(b)

[[[ 1  8]
  [ 9 10]
  [11 12]]

 [[ 0  1]
  [ 1  1]
  [ 1  1]]

 [[ 2 14]
  [15 16]
  [17 18]]]
[1 0 2]


In [6]:
#第二種方法

In [7]:
X = np.array([[0., 0.], [1., 1.], [2., 2.]])
y = np.array([0, 1, 2])
from sklearn.utils import shuffle
X, y = shuffle(X, y, random_state=1)
print(X)
print(y)

[[0. 0.]
 [2. 2.]
 [1. 1.]]
[0 2 1]


In [8]:
X = np.array([
     [[0, 1], [1, 1], [1, 1]],
     [[1, 8], [9, 10], [11, 12]],
     [[2, 14], [15, 16], [17, 18]]
     ])
X, y = shuffle(X, y, random_state=4)
print(X)
print(y)

[[[ 1  8]
  [ 9 10]
  [11 12]]

 [[ 0  1]
  [ 1  1]
  [ 1  1]]

 [[ 2 14]
  [15 16]
  [17 18]]]
[2 0 1]
